categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🚧 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
template: |
  ## What’s Changed

  $CHANGES
